#
# python-incremental
#
PYTHON_INCREMENTAL_VER    = 17.5.0
PYTHON_INCREMENTAL_DIR    = incremental-$(PYTHON_INCREMENTAL_VER)
PYTHON_INCREMENTAL_SOURCE = incremental-$(PYTHON_INCREMENTAL_VER).tar.gz
PYTHON_INCREMENTAL_URL    = https://files.pythonhosted.org/packages/source/i/incremental

$(ARCHIVE)/$(PYTHON_INCREMENTAL_SOURCE):
	$(DOWNLOAD) $(PYTHON_INCREMENTAL_URL)/$(PYTHON_INCREMENTAL_SOURCE)

$(D)/python-incremental: bootstrap python python-setuptools $(ARCHIVE)/$(PYTHON_INCREMENTAL_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON_INCREMENTAL_DIR)
	$(UNTAR)/$(PYTHON_INCREMENTAL_SOURCE)
	$(CHDIR)/$(PYTHON_INCREMENTAL_DIR); \
		$(PYTHON_BUILD); \
		$(PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON_INCREMENTAL_DIR)
	$(TOUCH)
