#
# python-pyopenssl
#
PYTHON_PYOPENSSL_VER    = 0.13.1
PYTHON_PYOPENSSL_DIR    = pyOpenSSL-$(PYTHON_PYOPENSSL_VER)
PYTHON_PYOPENSSL_SOURCE = pyOpenSSL-$(PYTHON_PYOPENSSL_VER).tar.gz
PYTHON_PYOPENSSL_URL    = https://pypi.python.org/packages/source/p/pyOpenSSL

$(ARCHIVE)/$(PYTHON_PYOPENSSL_SOURCE):
	$(DOWNLOAD) $(PYTHON_PYOPENSSL_URL)/$(PYTHON_PYOPENSSL_SOURCE)

PYTHON_PYOPENSSL_PATCH  = \
	python-pyopenssl.patch

$(D)/python-pyopenssl: bootstrap python python-setuptools $(ARCHIVE)/$(PYTHON_PYOPENSSL_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON_PYOPENSSL_DIR)
	$(UNTAR)/$(PYTHON_PYOPENSSL_SOURCE)
	$(CHDIR)/$(PYTHON_PYOPENSSL_DIR); \
		$(call apply_patches, $(PYTHON_PYOPENSSL_PATCH)); \
		$(PYTHON_BUILD); \
		$(PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON_PYOPENSSL_DIR)
	$(TOUCH)
