#
# annie's settingsupdater
#
NEUTRINO_SETTINGS_UPDATER_VER    = git
NEUTRINO_SETTINGS_UPDATER_DIR    = settings-updater.$(NEUTRINO_SETTINGS_UPDATER_VER)
NEUTRINO_SETTINGS_UPDATER_SOURCE = settings-updater.$(NEUTRINO_SETTINGS_UPDATER_VER)
NEUTRINO_SETTINGS_UPDATER_URL    = https://github.com/horsti58

$(D)/neutrino-settings-updater: bootstrap | $(SHARE_PLUGINS)
	$(START_BUILD)
	$(REMOVE)/$(NEUTRINO_SETTINGS_UPDATER_DIR)
	$(GET-GIT-SOURCE) $(NEUTRINO_SETTINGS_UPDATER_URL)/lua-data.git $(ARCHIVE)/$(NEUTRINO_SETTINGS_UPDATER_SOURCE)
	$(CPDIR)/$(NEUTRINO_SETTINGS_UPDATER_DIR)
	cp -a $(BUILD_DIR)/$(NEUTRINO_SETTINGS_UPDATER_DIR)/lua/* $(SHARE_PLUGINS)
	$(REMOVE)/$(NEUTRINO_SETTINGS_UPDATER_DIR)
	$(TOUCH)
