#
# python-zope-interface
#
PYTHON_ZOPE_INTERFACE_VER    = 4.5.0
PYTHON_ZOPE_INTERFACE_DIR    = zope.interface-$(PYTHON_ZOPE_INTERFACE_VER)
PYTHON_ZOPE_INTERFACE_SOURCE = zope.interface-$(PYTHON_ZOPE_INTERFACE_VER).tar.gz
PYTHON_ZOPE_INTERFACE_URL    = https://pypi.python.org/packages/source/z/zope.interface

$(ARCHIVE)/$(PYTHON_ZOPE_INTERFACE_SOURCE):
	$(DOWNLOAD) $(PYTHON_ZOPE_INTERFACE_URL)/$(PYTHON_ZOPE_INTERFACE_SOURCE)

$(D)/python-zope-interface: bootstrap python python-setuptools $(ARCHIVE)/$(PYTHON_ZOPE_INTERFACE_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON_ZOPE_INTERFACE_DIR)
	$(UNTAR)/$(PYTHON_ZOPE_INTERFACE_SOURCE)
	$(CHDIR)/$(PYTHON_ZOPE_INTERFACE_DIR); \
		$(PYTHON_BUILD); \
		$(PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON_ZOPE_INTERFACE_DIR)
	$(TOUCH)
