#
# python-service-identity
#
PYTHON_SERVICE_IDENTITY_VER    = 17.0.0
PYTHON_SERVICE_IDENTITY_DIR    = service_identity-$(PYTHON_SERVICE_IDENTITY_VER)
PYTHON_SERVICE_IDENTITY_SOURCE = service_identity-$(PYTHON_SERVICE_IDENTITY_VER).tar.gz
PYTHON_SERVICE_IDENTITY_URL    = https://pypi.python.org/packages/source/s/service_identity

$(ARCHIVE)/$(PYTHON_SERVICE_IDENTITY_SOURCE):
	$(DOWNLOAD) $(PYTHON_SERVICE_IDENTITY_URL)/$(PYTHON_SERVICE_IDENTITY_SOURCE)

$(D)/python-service-identity: bootstrap python python-setuptools python-attr python-attrs python-pyasn1 $(ARCHIVE)/$(PYTHON_SERVICE_IDENTITY_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON_SERVICE_IDENTITY_DIR)
	$(UNTAR)/$(PYTHON_SERVICE_IDENTITY_SOURCE)
	$(CHDIR)/$(PYTHON_SERVICE_IDENTITY_DIR); \
		$(PYTHON_BUILD); \
		$(PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON_SERVICE_IDENTITY_DIR)
	$(TOUCH)
