#
# wireguard-tools
#
WIREGUARD_TOOLS_VER    = 1.0.20200319
WIREGUARD_TOOLS_DIR    = wireguard-tools-$(WIREGUARD_TOOLS_VER)
WIREGUARD_TOOLS_SOURCE = wireguard-tools-$(WIREGUARD_TOOLS_VER).tar.xz
WIREGUARD_TOOLS_URL    = https://git.zx2c4.com/wireguard-tools/snapshot

$(ARCHIVE)/$(WIREGUARD_TOOLS_SOURCE):
	$(DOWNLOAD) $(WIREGUARD_TOOLS_URL)/$(WIREGUARD_TOOLS_SOURCE)

WIREGUARD_TOOLS_MAKE_OPTS = WITH_SYSTEMDUNITS=no WITH_BASHCOMPLETION=yes WITH_WGQUICK=yes

$(D)/wireguard-tools: bootstrap kernel libmnl openresolv $(ARCHIVE)/$(WIREGUARD_TOOLS_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(WIREGUARD_TOOLS_DIR)
	$(UNTAR)/$(WIREGUARD_TOOLS_SOURCE)
	$(CHDIR)/$(WIREGUARD_TOOLS_DIR)/src; \
		$(BUILD_ENV) \
		$(MAKE) all     $(WIREGUARD_TOOLS_MAKE_OPTS) PREFIX=/usr; \
		$(MAKE) install $(WIREGUARD_TOOLS_MAKE_OPTS) DESTDIR=$(TARGET_DIR) MANDIR=/.remove
	$(REMOVE)/$(WIREGUARD_TOOLS_DIR)
	$(TOUCH)
