#
# python3-setuptools
#
PYTHON3_SETUPTOOLS_VER    = 44.0.0
PYTHON3_SETUPTOOLS_DIR    = setuptools-$(PYTHON3_SETUPTOOLS_VER)
PYTHON3_SETUPTOOLS_SOURCE = setuptools-$(PYTHON3_SETUPTOOLS_VER).zip
PYTHON3_SETUPTOOLS_URL    = https://files.pythonhosted.org/packages/b0/f3/44da7482ac6da3f36f68e253cb04de37365b3dba9036a3c70773b778b485

$(ARCHIVE)/$(PYTHON3_SETUPTOOLS_SOURCE):
	$(DOWNLOAD) $(PYTHON3_SETUPTOOLS_URL)/$(PYTHON3_SETUPTOOLS_SOURCE)

PYTHON3_SETUPTOOLS_PATCH = \
	0001-add-executable.patch

$(D)/python3-setuptools: bootstrap host-python3 $(ARCHIVE)/$(PYTHON3_SETUPTOOLS_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON3_SETUPTOOLS_DIR)
	unzip -o $(SILENT_Q) $(ARCHIVE)/$(PYTHON3_SETUPTOOLS_SOURCE) -d $(BUILD_DIR)
	$(CHDIR)/$(PYTHON3_SETUPTOOLS_DIR); \
		$(call apply_patches, $(PYTHON3_SETUPTOOLS_PATCH)); \
		$(HOST_PYTHON_BUILD); \
		$(HOST_PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON3_SETUPTOOLS_DIR)
	$(TOUCH)
