#
# annie's settingsupdater
#
NEUTRINO_SETTINGSUPDATER_VER    = git
NEUTRINO_SETTINGSUPDATER_DIR    = settings-update.$(NEUTRINO_SETTINGSUPDATER_VER)
NEUTRINO_SETTINGSUPDATER_SOURCE = $(NEUTRINO_SETTINGSUPDATER_DIR)
NEUTRINO_SETTINGSUPDATER_URL    = $(GITHUB)/horsti58/lua-data.git

$(D)/neutrino-settings-update: bootstrap
	$(START_BUILD)
	$(REMOVE)/$(NEUTRINO_SETTINGSUPDATER_DIR)
	$(GET-GIT-SOURCE) $(NEUTRINO_SETTINGSUPDATER_URL) $(ARCHIVE)/$(NEUTRINO_SETTINGSUPDATER_SOURCE)
	$(CPDIR)/$(NEUTRINO_SETTINGSUPDATER_DIR)
	mkdir -p $(NP_DIR)
	cp -a $(BUILD_DIR)/$(NEUTRINO_SETTINGSUPDATER_DIR)/settings-update/lua/* $(NP_DIR)
	$(REMOVE)/$(NEUTRINO_SETTINGSUPDATER_DIR)
	$(TOUCH)
