#
# python-constantly
#
PYTHON_CONSTANTLY_VER    = 15.1.0
PYTHON_CONSTANTLY_DIR    = constantly-$(PYTHON_CONSTANTLY_VER)
PYTHON_CONSTANTLY_SOURCE = constantly-$(PYTHON_CONSTANTLY_VER).tar.gz
PYTHON_CONSTANTLY_URL    = https://files.pythonhosted.org/packages/source/c/constantly

$(ARCHIVE)/$(PYTHON_CONSTANTLY_SOURCE):
	$(DOWNLOAD) $(PYTHON_CONSTANTLY_URL)/$(PYTHON_CONSTANTLY_SOURCE)

$(D)/python-constantly: bootstrap python python-setuptools $(ARCHIVE)/$(PYTHON_CONSTANTLY_SOURCE)
	$(START_BUILD)
	$(REMOVE)/$(PYTHON_CONSTANTLY_DIR)
	$(UNTAR)/$(PYTHON_CONSTANTLY_SOURCE)
	$(CHDIR)/$(PYTHON_CONSTANTLY_DIR); \
		$(PYTHON_BUILD); \
		$(PYTHON_INSTALL)
	$(REMOVE)/$(PYTHON_CONSTANTLY_DIR)
	$(TOUCH)
