#
# neutrino-mediathek
#
NEUTRINO_MEDIATHEK_VER    = git
NEUTRINO_MEDIATHEK_DIR    = mediathek.$(NEUTRINO_MEDIATHEK_VER)
NEUTRINO_MEDIATHEK_SOURCE = mediathek.$(NEUTRINO_MEDIATHEK_VER)
NEUTRINO_MEDIATHEK_URL    = https://github.com/neutrino-mediathek

NEUTRINO_MEDIATHEK_PATCH  = \
	neutrino-mediathek.patch

$(D)/neutrino-mediathek: bootstrap | $(SHARE_PLUGINS)
	$(START_BUILD)
	$(REMOVE)/$(NEUTRINO_MEDIATHEK_DIR)
	$(GET-GIT-SOURCE) $(NEUTRINO_MEDIATHEK_URL)/$(NEUTRINO_MEDIATHEK_SOURCE) $(ARCHIVE)/$(NEUTRINO_MEDIATHEK_SOURCE)
	$(CPDIR)/$(NEUTRINO_MEDIATHEK_DIR)
	$(CHDIR)/$(NEUTRINO_MEDIATHEK_DIR); \
		$(call apply_patches, $(NEUTRINO_MEDIATHEK_PATCH)); \
	$(CHDIR)/$(NEUTRINO_MEDIATHEK_DIR); \
		cp -a plugins/* $(SHARE_PLUGINS); \
		cp -a share $(TARGET_DIR)/usr/
	$(REMOVE)/$(NEUTRINO_MEDIATHEK_DIR)
	$(TOUCH)
