#!/bin/sh
### BEGIN INIT INFO
# Provides:           resize2fs mmcblk0p3
# Required-Start:     $local_fs
# Required-Stop:      $local_fs
# Default-Start:      S
# Default-Stop:
# Short-Description:  Resizes once linuxrootfs and userdata to full partition size
### END INIT INFO

if ! test -e /.resizerootfs
then
    if grep -q mmcblk1p3 /proc/cmdline
    then
        echo "Resizing /dev/mmcblkp3, Do not unplug power!..."
        resize2fs /dev/mmcblk1p3
        touch /.resizerootfs
    fi
fi

: exit 0
