#
# vuzero4k-vmlinuz-initrd 7260a0
#
ifeq ($(VU_MULTIBOOT), 1)
VUZERO4K_VMLINUZ_INITRD_DATE   = 20190911
VUZERO4K_VMLINUZ_INITRD_URL    = https://bitbucket.org/max_10/vmlinuz-initrd-vuzero4k/downloads
else
VUZERO4K_VMLINUZ_INITRD_DATE   = 20170522
VUZERO4K_VMLINUZ_INITRD_URL    = http://archive.vuplus.com/download/kernel
endif
VUZERO4K_VMLINUZ_INITRD_VER    = $(VUZERO4K_VMLINUZ_INITRD_DATE)
VUZERO4K_VMLINUZ_INITRD_SOURCE = vmlinuz-initrd_vuzero4k_$(VUZERO4K_VMLINUZ_INITRD_VER).tar.gz

$(ARCHIVE)/$(VUZERO4K_VMLINUZ_INITRD_SOURCE):
	$(DOWNLOAD) $(VUZERO4K_VMLINUZ_INITRD_URL)/$(VUZERO4K_VMLINUZ_INITRD_SOURCE)

$(D)/vuzero4k-vmlinuz-initrd: bootstrap $(ARCHIVE)/$(VUZERO4K_VMLINUZ_INITRD_SOURCE)
	$(START_BUILD)
	tar -xf $(ARCHIVE)/$(VUZERO4K_VMLINUZ_INITRD_SOURCE) -C $(BUILD_DIR)
	$(TOUCH)
